version: "3.9"
services:
    detection-service:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "80:8000"
      environment:
          NODE_ENV: development
          PORT: 8000
          HOST: "0.0.0.0"
      command: ["npm", "run", "start"]
